---
title: "test-markdown"
author: "Fabien Roduit"
date: "2022-12-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


https://seymatas.medium.com/how-to-select-the-right-variables-from-a-large-dataset-ec56cce13d7


Libraries
```{r}
library(data.table)
library(corrplot)
library(dplyr)
library(ggplot2)
```

```{r}
cars <- fread("train.csv")

str(cars)



```

```{r}
cars <- cars %>%
           mutate(across(c(15:19,31:42), ~ifelse(.x=="Yes",1,0)))




cars[,c(5,7:13,15:19,20,22:24,31:44)] <- lapply(cars[,c(5,7:13,15:19,20,22:24,31:44)], factor)

cars <- cars[,-1]
str(cars)

```

```{r}
sum(apply(cars, 1, anyNA))
```



# Correlations
```{r}
corrplot(cor(cars[,c(1:3,5,13,20,25:29)]))
```





```{r}
models <- cars[,unique(model)]


for (model in models){
  
  print(model)
  
  print(sapply(cars[model==model], function(x) length(unique(x))) )
  
  print("__________")
  
}
```


# Domain knowledge

https://sheengroup.com.au/resources/information-centre/what-kinds-of-vehicles-get-in-the-most-accidents

Knowledge only
1,2,3,(4,5),8,(11/12/20),17,18,29,...

Further reducing
1,2,3,[4 or 5],8


Techniques

Using logistic regression
```{r}
set.seed(1)
index <- sample(nrow(cars),nrow(cars)*0.70)
cars_train = cars[index,]
cars_test = cars[-index,]

lg <- glm(is_claim~., family =binomial, data = cars_train)
```

```{r}
summary(lg)
```

```{r}
cars_glm_back <- step(lg) # backward selection (if you don't specify anything)
summary(cars_glm_back)
```

```{r}
cars[,unique(population_density),by=area_cluster]
```

```{r}
clusters <- unique(cars$area_cluster)

for (cluster in clusters){
  print(cluster)
  pop <- cars[area_cluster==as.character(cluster), cars$population_density ]
  print(summary(pop))
}

  pop <- cars[area_cluster=='C1', cars$population_density ]
  summary(pop)
```

```{r}
test <- cars[,.(mean =mean(population_density), median = median(population_density), nclaim = .N),by=list(area_cluster,is_claim)]


test[area_cluster == 'C16'] 
23/(378+23)
test[area_cluster == 'C22'] 
17/(190+17)
```

```{r}
lg2 <- glm(is_claim~., family =binomial, data = cars[,c(1,2,3,4,8,43)])
summary(lg2)
```

```{r}
t2 <-  cars[model=='M1',c(17,18,8,25:29)]
t3 <-  cars[model=='M2',4]


nrow(cars[model=="M6",])
nrow(cars[model=="M6" & ncap_rating==2,])
```

